version: '3'
services:
  web:
    image: emj365/leonfit
    networks:
      - default
      - traefik-net
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:shanghai-personaltraining.com"

networks:
  traefik-net:
    external: true
